version: '3.8'

services:

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cdrrmodb
      - POSTGRES_USER=jay
      - POSTGRES_PASSWORD=jay123
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cdrrmo
    restart: always

  cdrrmo-server:
    image: cdrrmo/cdrrmo-server:latest
    build:
      context: ./cdrrmo-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://jay:jay123@postgres:5432/cdrrmodb
      - NODE_ENV=production
      - PORT=3000
    networks:
      - cdrrmo
    restart: always


  cdrrmo-client:
    image: cdrrmo/cdrrmo-client:latest
    build:
      context: ./cdrrmo-client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    networks:
      - cdrrmo
    restart: always

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cdrrmo-client
      - cdrrmo-server
    networks:
      - cdrrmo
    restart: always

networks:
  cdrrmo:
    driver: bridge


volumes:
  postgres-data: